### ISSUE TITLE
transform for ONLY unknown categories fails

### ISSUE THREAD

**Issue by jhmenke** [yashu-seth/dummyPy#10]
If the encoder is fitted with some categories and a column of the test set has only new category values unknown to the encoder, it will throw an error:

>   File "C:\Users\Jan\Miniconda3\lib\site-packages\dummyPy\dummyPy.py", line 158, in transform
>     for column_name in data.columns]
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\dummyPy\dummyPy.py", line 158, in <listcomp>
>     for column_name in data.columns]
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\dummyPy\dummyPy.py", line 34, in transform
>     shape=(column_data.shape[0], len(self.column_mapper))))
>   File "C:\Users\Jan\Miniconda3\lib\site-packages\scipy\sparse\coo.py", line 142, in __init__
>     raise TypeError('invalid input format')
> TypeError: invalid input format
> 
> Process finished with exit code 1

Here 
https://github.com/yashu-seth/dummyPy/blob/12cf853f50bc21e24c8a6dc18f7cff581c6d9d35/dummyPy/dummyPy.py#L29
row_cols will be of length [], which causes a problem later.

There should just be an if clause which checks the length and if it's not existent return some default value (0.)

**Comment by yashu-seth** [comment]
@jhmenke Thanks for reporting this. Can you also share the code to reproduce the bug? It would be of great help.

**Comment by jhmenke** [comment]
Sure,

```
import dummyPy as dp
import pandas as pd


if __name__ == "__main__":
    r1 = ["S", "X", "T"]
    r2 = ["P", "X", "V"]
    r3 = ["S", "X", "T"]  # set r3 = ["D", "X", "T"] and it works
    r4 = ["D", "X", "Z"]
    r5 = ["D", "X", "V"]
    df = pd.DataFrame(columns=["A", "B", "C"], index=pd.RangeIndex(5), data=[r1, r2, r3, r4, r5])
    print(df)

    df1 = df.iloc[:3]
    df2 = df.iloc[3:]

    print(df1)
    print(df2)

    enc = dp.OneHotEncoder(categorical_columns=["A", "B", "C"])
    print(enc.fit_transform(df1))
    print(enc.transform(df2))
```

**Comment by jhmenke** [comment]
closed in pull request (please accept)
